;;;; Demo Theme - E-Commerce Visual Identity
;;;; Demonstrates how apps override lol-reactive tokens

(in-package :lol-reactive-demo)

;;; ============================================================================
;;; TOKEN OVERRIDES
;;; ============================================================================

(defun initialize-theme ()
  "Set up the demo app's custom theme tokens."

  ;; Modern dark e-commerce palette
  (setf lol-reactive:*colors*
        '((:background . "#0f0f1a")
          (:surface    . "#1a1a2e")
          (:primary    . "#6366f1")
          (:accent     . "#f472b6")
          (:text       . "#f1f5f9")
          (:muted      . "#64748b")
          (:success    . "#22c55e")
          (:warning    . "#eab308")
          (:error      . "#ef4444")))

  ;; Typography
  (setf lol-reactive:*typography*
        '((:family  . "system-ui, -apple-system, 'Segoe UI', sans-serif")
          (:mono    . "ui-monospace, 'Cascadia Code', monospace")
          (:massive . "3rem")
          (:huge    . "2rem")
          (:large   . "1.25rem")
          (:base    . "1rem")
          (:small   . "0.875rem")
          (:tiny    . "0.75rem")))

  ;; Spacing
  (setf lol-reactive:*spacing*
        '((:0  . "0")
          (:1  . "0.25rem")
          (:2  . "0.5rem")
          (:3  . "0.75rem")
          (:4  . "1rem")
          (:6  . "1.5rem")
          (:8  . "2rem")
          (:12 . "3rem"))))

;;; ============================================================================
;;; BASE STYLES
;;; ============================================================================

(defcss :demo-base
  ("*, *::before, *::after" (("box-sizing" . "border-box")))
  ("body" (("margin" . "0")
           ("padding" . "0")
           ("background" . "var(--color-background)")
           ("color" . "var(--color-text)")
           ("font-family" . "var(--font-family)")
           ("line-height" . "1.6")))
  ("h1, h2, h3, h4" (("margin" . "0 0 1rem 0")
                     ("line-height" . "1.2")))
  ("a" (("color" . "var(--color-primary)")
        ("text-decoration" . "none")))
  ("a:hover" (("text-decoration" . "underline"))))

;;; ============================================================================
;;; HEADER STYLES
;;; ============================================================================

(defcss :demo-header
  (".site-header" (("background" . "var(--color-surface)")
                   ("border-bottom" . "1px solid rgba(255,255,255,0.1)")
                   ("position" . "sticky")
                   ("top" . "0")
                   ("z-index" . "100")))
  (".header-content" (("max-width" . "1200px")
                      ("margin" . "0 auto")
                      ("padding" . "1rem 2rem")
                      ("display" . "flex")
                      ("align-items" . "center")
                      ("gap" . "2rem")))
  (".logo" (("display" . "flex")
            ("align-items" . "center")
            ("gap" . "0.5rem")
            ("font-size" . "1.5rem")
            ("font-weight" . "700")
            ("text-decoration" . "none")
            ("color" . "var(--color-text)")))
  (".logo-icon" (("font-size" . "1.75rem")))
  (".main-nav" (("display" . "flex")
                ("gap" . "1.5rem")
                ("margin-right" . "auto")))
  (".nav-link" (("color" . "var(--color-muted)")
                ("text-decoration" . "none")
                ("transition" . "color 0.2s")))
  (".nav-link:hover" (("color" . "var(--color-text)"))))

;;; ============================================================================
;;; CART STYLES
;;; ============================================================================

(defcss :demo-cart
  (".cart-summary" (("display" . "flex")
                    ("align-items" . "center")
                    ("gap" . "0.5rem")
                    ("padding" . "0.5rem 1rem")
                    ("background" . "var(--color-primary)")
                    ("border-radius" . "8px")
                    ("cursor" . "pointer")
                    ("position" . "relative")))
  (".cart-icon" (("font-size" . "1.25rem")))
  (".cart-count" (("background" . "var(--color-accent)")
                  ("color" . "white")
                  ("font-size" . "0.75rem")
                  ("font-weight" . "600")
                  ("padding" . "0.125rem 0.5rem")
                  ("border-radius" . "999px")
                  ("min-width" . "1.25rem")
                  ("text-align" . "center")))
  (".cart-total" (("font-weight" . "600")))
  (".cart-dropdown" (("position" . "absolute")
                     ("top" . "100%")
                     ("right" . "0")
                     ("margin-top" . "0.5rem")
                     ("width" . "320px")
                     ("background" . "var(--color-surface)")
                     ("border" . "1px solid rgba(255,255,255,0.1)")
                     ("border-radius" . "12px")
                     ("padding" . "1rem")
                     ("display" . "none")
                     ("box-shadow" . "0 20px 40px rgba(0,0,0,0.5)")))
  (".cart-dropdown.open" (("display" . "block")))
  (".cart-dropdown h4" (("margin" . "0 0 1rem 0")
                        ("padding-bottom" . "0.5rem")
                        ("border-bottom" . "1px solid rgba(255,255,255,0.1)")))
  (".cart-items" (("list-style" . "none")
                  ("margin" . "0")
                  ("padding" . "0")))
  (".cart-item" (("display" . "flex")
                 ("align-items" . "center")
                 ("gap" . "0.75rem")
                 ("padding" . "0.75rem 0")
                 ("border-bottom" . "1px solid rgba(255,255,255,0.05)")))
  (".cart-item:last-child" (("border-bottom" . "none")))
  (".cart-item .item-name" (("flex" . "1")
                            ("font-size" . "0.875rem")))
  (".cart-item .item-qty" (("display" . "flex")
                           ("align-items" . "center")
                           ("gap" . "0.25rem")))
  (".cart-item .item-price" (("font-weight" . "600")
                             ("color" . "var(--color-accent)")))
  (".qty-btn" (("width" . "24px")
               ("height" . "24px")
               ("border" . "1px solid var(--color-muted)")
               ("background" . "transparent")
               ("color" . "var(--color-text)")
               ("border-radius" . "4px")
               ("cursor" . "pointer")
               ("font-size" . "0.875rem")))
  (".qty-btn:hover" (("background" . "var(--color-primary)")))
  (".cart-footer" (("margin-top" . "1rem")
                   ("padding-top" . "1rem")
                   ("border-top" . "1px solid rgba(255,255,255,0.1)")))
  (".cart-total-line" (("display" . "flex")
                       ("justify-content" . "space-between")
                       ("margin-bottom" . "1rem")
                       ("font-weight" . "600")))
  (".total-amount" (("color" . "var(--color-accent)")
                    ("font-size" . "1.25rem")))
  (".checkout-btn" (("display" . "block")
                    ("width" . "100%")
                    ("padding" . "0.75rem")
                    ("background" . "var(--color-primary)")
                    ("color" . "white")
                    ("text-align" . "center")
                    ("border-radius" . "8px")
                    ("font-weight" . "600")
                    ("text-decoration" . "none")))
  (".checkout-btn:hover" (("background" . "#5355d1")
                          ("text-decoration" . "none")))
  (".empty-cart" (("color" . "var(--color-muted)")
                  ("text-align" . "center")
                  ("padding" . "1rem 0"))))

;;; ============================================================================
;;; HERO & LAYOUT STYLES
;;; ============================================================================

(defcss :demo-layout
  (".main-content" (("max-width" . "1200px")
                    ("margin" . "0 auto")
                    ("padding" . "2rem")))
  (".hero" (("text-align" . "center")
            ("padding" . "3rem 0")))
  (".hero h1" (("font-size" . "3rem")
               ("background" . "linear-gradient(135deg, var(--color-primary), var(--color-accent))")
               ("-webkit-background-clip" . "text")
               ("-webkit-text-fill-color" . "transparent")
               ("margin-bottom" . "0.5rem")))
  (".hero p" (("color" . "var(--color-muted)")
              ("font-size" . "1.125rem")))
  (".products-section h2" (("margin-bottom" . "1.5rem"))))

;;; ============================================================================
;;; PRODUCT GRID STYLES
;;; ============================================================================

(defcss :demo-products
  (".product-grid" (("display" . "grid")
                    ("grid-template-columns" . "repeat(auto-fill, minmax(280px, 1fr))")
                    ("gap" . "1.5rem")))
  (".product-card" (("background" . "var(--color-surface)")
                    ("border-radius" . "16px")
                    ("overflow" . "hidden")
                    ("transition" . "transform 0.2s, box-shadow 0.2s")))
  (".product-card:hover" (("transform" . "translateY(-4px)")
                          ("box-shadow" . "0 12px 40px rgba(99, 102, 241, 0.15)")))
  (".product-image" (("height" . "160px")
                     ("display" . "flex")
                     ("align-items" . "center")
                     ("justify-content" . "center")
                     ("background" . "linear-gradient(135deg, rgba(99,102,241,0.1), rgba(244,114,182,0.1))")
                     ("font-size" . "4rem")))
  (".product-info" (("padding" . "1.25rem")))
  (".product-name" (("font-size" . "1.125rem")
                    ("margin" . "0 0 0.5rem 0")))
  (".product-description" (("color" . "var(--color-muted)")
                           ("font-size" . "0.875rem")
                           ("margin" . "0 0 1rem 0")
                           ("line-height" . "1.5")))
  (".product-footer" (("display" . "flex")
                      ("align-items" . "center")
                      ("justify-content" . "space-between")))
  (".product-price" (("font-size" . "1.25rem")
                     ("font-weight" . "700")
                     ("color" . "var(--color-accent)")))
  (".add-to-cart-btn" (("padding" . "0.5rem 1rem")
                       ("background" . "var(--color-primary)")
                       ("color" . "white")
                       ("border" . "none")
                       ("border-radius" . "8px")
                       ("cursor" . "pointer")
                       ("font-weight" . "600")
                       ("transition" . "background 0.2s")))
  (".add-to-cart-btn:hover" (("background" . "#5355d1"))))

;;; ============================================================================
;;; CHECKOUT & WIZARD STYLES
;;; ============================================================================

(defcss :demo-checkout
  (".checkout-page" (("padding-top" . "1rem")))
  (".checkout-container" (("max-width" . "600px")
                          ("margin" . "0 auto")))
  (".wizard" (("background" . "var(--color-surface)")
              ("border-radius" . "16px")
              ("padding" . "2rem")))
  (".wizard-progress" (("margin-bottom" . "2rem")))
  (".wizard-step-indicator" (("font-size" . "0.875rem")
                             ("color" . "var(--color-muted)")))
  (".wizard-step-indicator.text-primary" (("color" . "var(--color-primary)")))
  (".wizard-step-indicator.text-success" (("color" . "var(--color-success)")))
  (".wizard h2" (("font-size" . "1.5rem")
                 ("margin-bottom" . "1.5rem")))
  (".form-section" (("display" . "flex")
                    ("flex-direction" . "column")
                    ("gap" . "1rem")))
  (".form-row" (("display" . "grid")
                ("grid-template-columns" . "1fr 1fr")
                ("gap" . "1rem")))
  (".wizard-nav" (("display" . "flex")
                  ("justify-content" . "space-between")
                  ("margin-top" . "2rem")
                  ("padding-top" . "1.5rem")
                  ("border-top" . "1px solid rgba(255,255,255,0.1)")))
  (".wizard input[type=text], .wizard select" (("width" . "100%")
                                                ("padding" . "0.75rem 1rem")
                                                ("background" . "var(--color-background)")
                                                ("border" . "1px solid rgba(255,255,255,0.1)")
                                                ("border-radius" . "8px")
                                                ("color" . "var(--color-text)")
                                                ("font-size" . "1rem")))
  (".wizard input[type=text]:focus, .wizard select:focus" (("outline" . "none")
                                                            ("border-color" . "var(--color-primary)")))
  (".wizard label" (("display" . "block")
                    ("margin-bottom" . "0.5rem")
                    ("font-weight" . "500")))
  (".wizard button[type=submit]" (("padding" . "0.75rem 1.5rem")
                                   ("border" . "none")
                                   ("border-radius" . "8px")
                                   ("cursor" . "pointer")
                                   ("font-weight" . "600")
                                   ("font-size" . "1rem")))
  (".wizard button[value=next], .wizard button[value=complete]" (("background" . "var(--color-primary)")
                                                                  ("color" . "white")))
  (".wizard button[value=back]" (("background" . "transparent")
                                  ("border" . "1px solid var(--color-muted)")
                                  ("color" . "var(--color-text)"))))

;;; ============================================================================
;;; ORDER CONFIRMATION STYLES
;;; ============================================================================

(defcss :demo-confirmation
  (".order-complete" (("text-align" . "center")
                      ("padding" . "4rem 2rem")
                      ("background" . "var(--color-surface)")
                      ("border-radius" . "16px")
                      ("max-width" . "500px")
                      ("margin" . "0 auto")))
  (".success-icon" (("width" . "80px")
                    ("height" . "80px")
                    ("margin" . "0 auto 1.5rem")
                    ("display" . "flex")
                    ("align-items" . "center")
                    ("justify-content" . "center")
                    ("background" . "var(--color-success)")
                    ("color" . "white")
                    ("font-size" . "2.5rem")
                    ("border-radius" . "50%")))
  (".order-complete h2" (("margin-bottom" . "0.5rem")))
  (".order-id" (("color" . "var(--color-muted)")
                ("font-size" . "0.875rem")
                ("margin-bottom" . "1rem")))
  (".continue-shopping" (("display" . "inline-block")
                         ("margin-top" . "1.5rem")
                         ("padding" . "0.75rem 2rem")
                         ("background" . "var(--color-primary)")
                         ("color" . "white")
                         ("border-radius" . "8px")
                         ("text-decoration" . "none"))))

;;; ============================================================================
;;; REVIEW STEP STYLES
;;; ============================================================================

(defcss :demo-review
  (".review-section h4" (("margin" . "1.5rem 0 1rem 0")
                         ("color" . "var(--color-muted)")
                         ("font-size" . "0.875rem")
                         ("text-transform" . "uppercase")
                         ("letter-spacing" . "0.05em")))
  (".review-section h4:first-child" (("margin-top" . "0")))
  (".review-items" (("background" . "var(--color-background)")
                    ("border-radius" . "8px")
                    ("padding" . "1rem")))
  (".review-item" (("display" . "flex")
                   ("justify-content" . "space-between")
                   ("padding" . "0.5rem 0")
                   ("border-bottom" . "1px solid rgba(255,255,255,0.05)")))
  (".review-item:last-child" (("border-bottom" . "none")))
  (".review-total" (("display" . "flex")
                    ("justify-content" . "space-between")
                    ("padding" . "1rem")
                    ("background" . "var(--color-background)")
                    ("border-radius" . "8px")
                    ("font-weight" . "600")
                    ("font-size" . "1.125rem")))
  (".shipping-summary" (("background" . "var(--color-background)")
                        ("border-radius" . "8px")
                        ("padding" . "1rem")))
  (".shipping-summary p" (("margin" . "0.25rem 0")))
  (".terms-checkbox" (("margin-top" . "1.5rem")
                      ("padding" . "1rem")
                      ("background" . "rgba(99,102,241,0.1)")
                      ("border-radius" . "8px")))
  (".terms-checkbox label" (("display" . "flex")
                            ("align-items" . "center")
                            ("gap" . "0.5rem")
                            ("cursor" . "pointer")))
  (".terms-checkbox input[type=checkbox]" (("width" . "18px")
                                           ("height" . "18px"))))

;;; ============================================================================
;;; TOAST NOTIFICATION STYLES
;;; ============================================================================

(defcss :demo-toast
  (".toast" (("position" . "fixed")
             ("bottom" . "2rem")
             ("left" . "50%")
             ("transform" . "translateX(-50%)")
             ("background" . "var(--color-success)")
             ("color" . "white")
             ("padding" . "0.75rem 1.5rem")
             ("border-radius" . "8px")
             ("font-weight" . "600")
             ("animation" . "toast-in 0.3s ease")))
  ("@keyframes toast-in" (("from" . (("opacity" . "0") ("transform" . "translateX(-50%) translateY(20px)")))
                          ("to" . (("opacity" . "1") ("transform" . "translateX(-50%) translateY(0)"))))))

;;; ============================================================================
;;; EMPTY STATE STYLES
;;; ============================================================================

(defcss :demo-empty
  (".empty-checkout" (("text-align" . "center")
                      ("padding" . "4rem 2rem")
                      ("background" . "var(--color-surface)")
                      ("border-radius" . "16px")
                      ("max-width" . "500px")
                      ("margin" . "2rem auto")))
  (".empty-checkout h2" (("margin-bottom" . "0.5rem")))
  (".empty-checkout p" (("color" . "var(--color-muted)")
                        ("margin-bottom" . "1.5rem"))))
